import { Framework } from "../types/framework";

export const initialFrameworks: Framework[] = [
  {
    "id": "DIR-SERVICES",
    "name": "Directory Services",
    "version": "1.0",
    "description": "Controls and mappings for directory (AD/Entra) integration and governance.",
    "category": "Security",
    "isActive": true,
    "effectiveDate": "2026-03-22",
    "notes": "Canonical mappings from legacy DIR-* tokens to RBAC-INT-* requirements.",
    "controls": [
      {
        "id": "DIR-CTRL-INT-1",
        "frameworkId": "DIR-SERVICES",
        "controlId": "DIR-INT-1",
        "title": "IGA / Directory integration",
        "description": "Integration between IGA platform and directory services to ingest accounts and groups.",
        "requirements": [
          "RBAC-INT-005",
          "RBAC-INT-006",
          "RBAC-IGA-024",
          "RBAC-IGA-025"
        ],
        "category": "Directory",
        "priority": "High",
        "notes": "maps from legacy DIR-INT-1"
      },
      {
        "id": "DIR-CTRL-PRV-2.1",
        "frameworkId": "DIR-SERVICES",
        "controlId": "DIR-2.1",
        "title": "Directory group provisioning",
        "description": "Ensure directory group memberships are provisioned/updated from RBAC/IGA decisions.",
        "requirements": [
          "RBAC-INT-008",
          "RBAC-INT-017"
        ],
        "category": "Directory",
        "priority": "High",
        "notes": "maps from legacy DIR-2.1"
      },
      {
        "id": "DIR-CTRL-DRIFT-3.1",
        "frameworkId": "DIR-SERVICES",
        "controlId": "DIR-3.1",
        "title": "Out-of-band change detection",
        "description": "Detect and report out-of-band changes to directory groups and memberships.",
        "requirements": [
          "RBAC-INT-010"
        ],
        "category": "Directory",
        "priority": "High",
        "notes": "maps from legacy DIR-3.1"
      },
      {
        "id": "DIR-CTRL-LOG-6.1",
        "frameworkId": "DIR-SERVICES",
        "controlId": "DIR-6.1",
        "title": "Directory event logging",
        "description": "Log directory events impacting access (create/update/delete) with attribution and before/after state.",
        "requirements": [],
        "category": "Directory",
        "priority": "Medium",
        "notes": "maps from legacy DIR-6.1"
      }
    ]
  },
  {
    "id": "SOX-FRAMEWORK",
    "name": "SOX Controls",
    "version": "1.0",
    "description": "SOX control mappings generated by heuristic mapper",
    "category": "Compliance",
    "isActive": true,
    "effectiveDate": "2026-03-22",
    "notes": "Auto-generated minimal framework for heuristic mapping",
    "controls": [
      {
        "id": "SOX-FRAMEWORK-C-1",
        "frameworkId": "SOX-FRAMEWORK",
        "controlId": "SOX-ITGC-01",
        "title": "SOX-ITGC-01 (auto)",
        "description": "Auto-generated control stub for SOX-ITGC-01",
        "requirements": [
          "RBAC-ENT-003",
          "RBAC-ENT-004",
          "RBAC-CAP-109",
          "RBAC-CAP-208",
          "RBAC-CAP-209",
          "RBAC-CAP-304",
          "RBAC-CAP-403",
          "RBAC-CAP-407",
          "RBAC-CAP-502",
          "RBAC-CAP-503",
          "RBAC-CAP-504",
          "RBAC-CAP-505",
          "RBAC-CAP-603",
          "RBAC-CAP-605",
          "RBAC-CAP-703",
          "RBAC-CAP-704",
          "RBAC-CAP-804",
          "RBAC-IGA-005",
          "RBAC-IGA-011",
          "RBAC-IGA-014",
          "RBAC-IGA-016",
          "RBAC-IGA-017",
          "RBAC-IGA-019",
          "RBAC-IGA-036",
          "RBAC-IGA-037",
          "RBAC-IGA-038",
          "RBAC-IGA-039",
          "RBAC-IGA-040",
          "RBAC-IGA-042",
          "RBAC-INT-004",
          "RBAC-INT-011",
          "RBAC-INT-019",
          "RBAC-NFR-003",
          "RBAC-NFR-006",
          "RBAC-NFR-008",
          "RBAC-NFR-012"
        ]
      },
      {
        "id": "SOX-FRAMEWORK-C-2",
        "frameworkId": "SOX-FRAMEWORK",
        "controlId": "SOX-ITGC-02",
        "title": "SOX-ITGC-02 (auto)",
        "description": "Auto-generated control stub for SOX-ITGC-02",
        "requirements": []
      },
      {
        "id": "SOX-FRAMEWORK-C-3",
        "frameworkId": "SOX-FRAMEWORK",
        "controlId": "SOX-ITGC-04",
        "title": "SOX-ITGC-04 (auto)",
        "description": "Auto-generated control stub for SOX-ITGC-04",
        "requirements": []
      }
    ]
  },
  {
    "id": "NIST-FRAMEWORK",
    "name": "NIST Controls",
    "version": "1.0",
    "description": "NIST control mappings generated by heuristic mapper",
    "category": "Compliance",
    "isActive": true,
    "effectiveDate": "2026-03-22",
    "notes": "Auto-generated minimal framework for heuristic mapping",
    "controls": [
      {
        "id": "NIST-FRAMEWORK-C-1",
        "frameworkId": "NIST-FRAMEWORK",
        "controlId": "AC-2",
        "title": "AC-2 (auto)",
        "description": "Auto-generated control stub for AC-2",
        "requirements": [
          "RBAC-ENT-001",
          "RBAC-ENT-002",
          "RBAC-CAP-105",
          "RBAC-CAP-106",
          "RBAC-CAP-110",
          "RBAC-CAP-202",
          "RBAC-CAP-205",
          "RBAC-CAP-301",
          "RBAC-CAP-302",
          "RBAC-CAP-303",
          "RBAC-CAP-305",
          "RBAC-CAP-401",
          "RBAC-CAP-404",
          "RBAC-CAP-405",
          "RBAC-CAP-406",
          "RBAC-CAP-501",
          "RBAC-CAP-601",
          "RBAC-CAP-604",
          "RBAC-CAP-701",
          "RBAC-CAP-702",
          "RBAC-IGA-001",
          "RBAC-IGA-003",
          "RBAC-IGA-004",
          "RBAC-IGA-009",
          "RBAC-IGA-010",
          "RBAC-IGA-012",
          "RBAC-IGA-013",
          "RBAC-IGA-015",
          "RBAC-IGA-018",
          "RBAC-IGA-020",
          "RBAC-IGA-022",
          "RBAC-IGA-023",
          "RBAC-IGA-026",
          "RBAC-IGA-027",
          "RBAC-NFR-008",
          "RBAC-CAP-107",
          "RBAC-CAP-602",
          "RBAC-IGA-029",
          "RBAC-IGA-030",
          "RBAC-IGA-033",
          "RBAC-IGA-034",
          "RBAC-IGA-035",
          "RBAC-IGA-041",
          "RBAC-INT-002",
          "RBAC-INT-003",
          "RBAC-INT-007",
          "RBAC-INT-009",
          "RBAC-INT-012",
          "RBAC-INT-013",
          "RBAC-NFR-009",
          "RBAC-CAP-101",
          "RBAC-CAP-102",
          "RBAC-CAP-801",
          "RBAC-CAP-802",
          "RBAC-IGA-007",
          "RBAC-IGA-008",
          "RBAC-INT-015",
          "RBAC-INT-016",
          "RBAC-INT-018",
          "RBAC-NFR-001",
          "RBAC-NFR-002",
          "RBAC-NFR-004",
          "RBAC-NFR-010",
          "RBAC-NFR-011"
        ]
      },
      {
        "id": "NIST-FRAMEWORK-C-2",
        "frameworkId": "NIST-FRAMEWORK",
        "controlId": "AC-3",
        "title": "AC-3 (auto)",
        "description": "Auto-generated control stub for AC-3",
        "requirements": []
      },
      {
        "id": "NIST-FRAMEWORK-C-3",
        "frameworkId": "NIST-FRAMEWORK",
        "controlId": "AC-5",
        "title": "AC-5 (auto)",
        "description": "Auto-generated control stub for AC-5",
        "requirements": []
      },
      {
        "id": "NIST-FRAMEWORK-C-4",
        "frameworkId": "NIST-FRAMEWORK",
        "controlId": "AC-6",
        "title": "AC-6 (auto)",
        "description": "Auto-generated control stub for AC-6",
        "requirements": []
      },
      {
        "id": "NIST-FRAMEWORK-C-5",
        "frameworkId": "NIST-FRAMEWORK",
        "controlId": "IA-2",
        "title": "IA-2 (auto)",
        "description": "Auto-generated control stub for IA-2",
        "requirements": []
      }
    ]
  },
  {
    "id": "ISO-FRAMEWORK",
    "name": "ISO Controls",
    "version": "1.0",
    "description": "ISO control mappings generated by heuristic mapper",
    "category": "Compliance",
    "isActive": true,
    "effectiveDate": "2026-03-22",
    "notes": "Auto-generated minimal framework for heuristic mapping",
    "controls": [
      {
        "id": "ISO-FRAMEWORK-C-1",
        "frameworkId": "ISO-FRAMEWORK",
        "controlId": "A.9.1.1",
        "title": "A.9.1.1 (auto)",
        "description": "Auto-generated control stub for A.9.1.1",
        "requirements": [
          "RBAC-ENT-005",
          "RBAC-ENT-006",
          "RBAC-CAP-104",
          "RBAC-CAP-203",
          "RBAC-CAP-204",
          "RBAC-CAP-402",
          "RBAC-NFR-007",
          "RBAC-CAP-103",
          "RBAC-CAP-201"
        ]
      },
      {
        "id": "ISO-FRAMEWORK-C-2",
        "frameworkId": "ISO-FRAMEWORK",
        "controlId": "A.9.1.2",
        "title": "A.9.1.2 (auto)",
        "description": "Auto-generated control stub for A.9.1.2",
        "requirements": []
      },
      {
        "id": "ISO-FRAMEWORK-C-3",
        "frameworkId": "ISO-FRAMEWORK",
        "controlId": "A.9.2.1",
        "title": "A.9.2.1 (auto)",
        "description": "Auto-generated control stub for A.9.2.1",
        "requirements": []
      },
      {
        "id": "ISO-FRAMEWORK-C-4",
        "frameworkId": "ISO-FRAMEWORK",
        "controlId": "A.9.2.2",
        "title": "A.9.2.2 (auto)",
        "description": "Auto-generated control stub for A.9.2.2",
        "requirements": []
      }
    ]
  },
  {
    "id": "COBIT-FRAMEWORK",
    "name": "COBIT Controls",
    "version": "1.0",
    "description": "COBIT control mappings generated by heuristic mapper",
    "category": "Compliance",
    "isActive": true,
    "effectiveDate": "2026-03-22",
    "notes": "Auto-generated minimal framework for heuristic mapping",
    "controls": [
      {
        "id": "COBIT-FRAMEWORK-C-1",
        "frameworkId": "COBIT-FRAMEWORK",
        "controlId": "DSS05.04",
        "title": "DSS05.04 (auto)",
        "description": "Auto-generated control stub for DSS05.04",
        "requirements": [
          "RBAC-CAP-108",
          "RBAC-CAP-206",
          "RBAC-CAP-803",
          "RBAC-IGA-006",
          "RBAC-IGA-031",
          "RBAC-IGA-032",
          "RBAC-INT-001",
          "RBAC-INT-014",
          "RBAC-NFR-005",
          "RBAC-CAP-101",
          "RBAC-CAP-102",
          "RBAC-CAP-801",
          "RBAC-CAP-802",
          "RBAC-IGA-007",
          "RBAC-IGA-008",
          "RBAC-INT-015",
          "RBAC-INT-016",
          "RBAC-INT-018",
          "RBAC-NFR-001",
          "RBAC-NFR-002",
          "RBAC-NFR-004",
          "RBAC-NFR-010",
          "RBAC-NFR-011"
        ],
      },
      {
        "id": "COBIT-FRAMEWORK-C-2",
        "frameworkId": "COBIT-FRAMEWORK",
        "controlId": "DSS05.05",
        "title": "DSS05.05 (auto)",
        "description": "Auto-generated control stub for DSS05.05",
        "requirements": []
      },
      {
        "id": "COBIT-FRAMEWORK-C-3",
        "frameworkId": "COBIT-FRAMEWORK",
        "controlId": "APO13.01",
        "title": "APO13.01 (auto)",
        "description": "Auto-generated control stub for APO13.01",
        "requirements": []
      }
    ]
  }
];
