import { StoryMap } from "../types/storymap";

export const initialStoryMap: StoryMap = [
  {
    "id": "OUT-1774385506119",
    "title": "Auto-generated story map (from epics & stories)",
    "description": "Generated by scripts/generate-initial-storymap.mjs",
    "activities": [
      {
        "id": "EPIC-1",
        "title": "Application Discovery & Onboarding",
        "description": "Build standardized application discovery and onboarding workflow with evidence retention",
        "order": 1,
        "steps": [
          {
            "id": "US-1.1",
            "title": "The system SHALL enforce least privilege access by ensuring users receive only the access required for their job function and by explicitly identifying and governing privileged or sensitive access",
            "description": "The system SHALL enforce least privilege access by ensuring users receive only the access required for their job function and by explicitly identifying and governing privileged or sensitive access",
            "order": 3
          },
          {
            "id": "US-1.2",
            "title": "The system SHALL provide a standardized discovery model to capture application RBAC readiness inputs",
            "description": "The system SHALL provide a standardized discovery model to capture application RBAC readiness inputs",
            "order": 3
          },
          {
            "id": "US-1.3",
            "title": "The system SHALL require completion of minimum discovery criteria before entitlement mapping",
            "description": "The system SHALL require completion of minimum discovery criteria before entitlement mapping",
            "order": 3
          },
          {
            "id": "US-1.4",
            "title": "The system SHALL require identification of business and technical owners",
            "description": "The system SHALL require identification of business and technical owners",
            "order": 3
          },
          {
            "id": "US-1.5",
            "title": "The system SHALL require a current permission inventory",
            "description": "The system SHALL require a current permission inventory",
            "order": 3
          },
          {
            "id": "US-1.6",
            "title": "The system SHALL identify privileged access paths during discovery",
            "description": "The system SHALL identify privileged access paths during discovery",
            "order": 3
          },
          {
            "id": "US-1.7",
            "title": "The system SHALL capture segregation-of-duties considerations",
            "description": "The system SHALL capture segregation-of-duties considerations",
            "order": 3
          },
          {
            "id": "US-1.8",
            "title": "The system SHALL track discovery lifecycle status",
            "description": "The system SHALL track discovery lifecycle status",
            "order": 3
          },
          {
            "id": "US-1.9",
            "title": "The system SHALL support RBAC governance for non-human identities",
            "description": "The system SHALL support RBAC governance for non-human identities",
            "order": 3
          },
          {
            "id": "US-1.10",
            "title": "The system SHALL flag privileged entitlements during mapping",
            "description": "The system SHALL flag privileged entitlements during mapping",
            "order": 3
          },
          {
            "id": "US-1.11",
            "title": "The system SHALL apply privileged designation using governance criteria",
            "description": "The system SHALL apply privileged designation using governance criteria",
            "order": 3
          },
          {
            "id": "US-1.12",
            "title": "The system SHALL route approvals based on governance rules",
            "description": "The system SHALL route approvals based on governance rules",
            "order": 3
          },
          {
            "id": "US-1.13",
            "title": "The system SHALL record approval decisions as evidence",
            "description": "The system SHALL record approval decisions as evidence",
            "order": 3
          },
          {
            "id": "US-1.14",
            "title": "The system SHALL prevent fulfillment without approvals",
            "description": "The system SHALL prevent fulfillment without approvals",
            "order": 3
          },
          {
            "id": "US-1.15",
            "title": "Automatically revoke JIT access",
            "description": "Automatically revoke JIT access",
            "order": 3
          },
          {
            "id": "US-1.16",
            "title": "The system SHALL support documented access exceptions",
            "description": "The system SHALL support documented access exceptions",
            "order": 3
          },
          {
            "id": "US-1.17",
            "title": "The system SHALL enforce expiration or revalidation of exceptions",
            "description": "The system SHALL enforce expiration or revalidation of exceptions",
            "order": 3
          },
          {
            "id": "US-1.18",
            "title": "The system SHALL support emergency (break glass) access with review",
            "description": "The system SHALL support emergency (break glass) access with review",
            "order": 3
          },
          {
            "id": "US-1.19",
            "title": "The system SHALL retain exception and emergency evidence",
            "description": "The system SHALL retain exception and emergency evidence",
            "order": 3
          },
          {
            "id": "US-1.20",
            "title": "The system SHALL report who has access and why",
            "description": "The system SHALL report who has access and why",
            "order": 3
          },
          {
            "id": "US-1.21",
            "title": "The system SHALL retain historical access records",
            "description": "The system SHALL retain historical access records",
            "order": 3
          },
          {
            "id": "US-1.22",
            "title": "The system SHALL ensure evidence is complete and attributable",
            "description": "The system SHALL ensure evidence is complete and attributable",
            "order": 3
          }
        ]
      },
      {
        "id": "EPIC-2",
        "title": "Business Role Management",
        "description": "Enable creation, lifecycle management, and composition of business roles",
        "order": 2,
        "steps": [
          {
            "id": "US-2.1",
            "title": "Establish a standardized, enterprise role-based access governance model that def...",
            "description": "Establish a standardized, enterprise role-based access governance model that defines roles, maps roles to entitlements, and governs access decisions consistently across applications",
            "order": 3
          },
          {
            "id": "US-2.2",
            "title": "The system SHALL require documented role constructs or confirmation none exist",
            "description": "The system SHALL require documented role constructs or confirmation none exist",
            "order": 3
          },
          {
            "id": "US-2.3",
            "title": "The system SHALL support explicit definition of business roles",
            "description": "The system SHALL support explicit definition of business roles",
            "order": 3
          },
          {
            "id": "US-2.4",
            "title": "The system SHALL enforce role eligibility criteria",
            "description": "The system SHALL enforce role eligibility criteria",
            "order": 3
          },
          {
            "id": "US-2.5",
            "title": "The system SHALL require documented role purpose and owner",
            "description": "The system SHALL require documented role purpose and owner",
            "order": 3
          },
          {
            "id": "US-2.6",
            "title": "The system SHALL support role lifecycle states",
            "description": "The system SHALL support role lifecycle states",
            "order": 3
          },
          {
            "id": "US-2.7",
            "title": "The system SHALL ensure users inherit access only through roles",
            "description": "The system SHALL ensure users inherit access only through roles",
            "order": 3
          },
          {
            "id": "US-2.8",
            "title": "The system SHALL automatically revoke access when role removed",
            "description": "The system SHALL automatically revoke access when role removed",
            "order": 3
          },
          {
            "id": "US-2.9",
            "title": "The system SHALL support role composition",
            "description": "The system SHALL support role composition",
            "order": 3
          },
          {
            "id": "US-2.10",
            "title": "The system SHALL support periodic role review",
            "description": "The system SHALL support periodic role review",
            "order": 3
          },
          {
            "id": "US-2.11",
            "title": "The system SHALL require approval and justification for material role changes",
            "description": "The system SHALL require approval and justification for material role changes",
            "order": 3
          },
          {
            "id": "US-2.12",
            "title": "The system SHALL enforce role-to-permission mapping",
            "description": "The system SHALL enforce role-to-permission mapping",
            "order": 3
          },
          {
            "id": "US-2.13",
            "title": "The system SHALL require justification for permissions in roles",
            "description": "The system SHALL require justification for permissions in roles",
            "order": 3
          },
          {
            "id": "US-2.14",
            "title": "The system SHALL require role owner approval for permission changes",
            "description": "The system SHALL require role owner approval for permission changes",
            "order": 3
          },
          {
            "id": "US-2.15",
            "title": "The system SHALL support role-based access requests",
            "description": "The system SHALL support role-based access requests",
            "order": 3
          },
          {
            "id": "US-2.16",
            "title": "The system SHALL support time-bound / JIT role activation",
            "description": "The system SHALL support time-bound / JIT role activation",
            "order": 3
          },
          {
            "id": "US-2.17",
            "title": "The system SHALL trigger role review from repeated exceptions",
            "description": "The system SHALL trigger role review from repeated exceptions",
            "order": 3
          },
          {
            "id": "US-2.18",
            "title": "IGA is system of record for roles and assignments",
            "description": "IGA is system of record for roles and assignments",
            "order": 3
          },
          {
            "id": "US-2.19",
            "title": "The system SHALL correlate accounts and entitlements to roles",
            "description": "The system SHALL correlate accounts and entitlements to roles",
            "order": 3
          },
          {
            "id": "US-2.20",
            "title": "The system SHALL enforce RBAC role execution",
            "description": "The system SHALL enforce RBAC role execution",
            "order": 3
          },
          {
            "id": "US-2.21",
            "title": "The system SHALL ingest identity attributes from Workday to drive role eligibility",
            "description": "The system SHALL ingest identity attributes from Workday to drive role eligibility",
            "order": 3
          },
          {
            "id": "US-2.22",
            "title": "The system SHALL map directory groups to roles",
            "description": "The system SHALL map directory groups to roles",
            "order": 3
          },
          {
            "id": "US-2.23",
            "title": "Revoke directory access on role removal",
            "description": "Revoke directory access on role removal",
            "order": 3
          }
        ]
      },
      {
        "id": "EPIC-3",
        "title": "Privileged Access Governance",
        "description": "Implement privileged entitlement flagging and governance controls",
        "order": 3,
        "steps": []
      },
      {
        "id": "EPIC-4",
        "title": "Access Request & Lifecycle",
        "description": "Build role-based access request system with automated lifecycle management",
        "order": 4,
        "steps": []
      },
      {
        "id": "EPIC-5",
        "title": "Access Certification & Review",
        "description": "Create periodic access certification campaigns with automated revocation",
        "order": 5,
        "steps": [
          {
            "id": "US-5.1",
            "title": "The system SHALL support periodic access certifications",
            "description": "The system SHALL support periodic access certifications",
            "order": 3
          },
          {
            "id": "US-5.2",
            "title": "The system SHALL assign certifiers by governance rules",
            "description": "The system SHALL assign certifiers by governance rules",
            "order": 3
          },
          {
            "id": "US-5.3",
            "title": "The system SHALL record certification decisions",
            "description": "The system SHALL record certification decisions",
            "order": 3
          },
          {
            "id": "US-5.4",
            "title": "The system SHALL trigger actions from certification outcomes",
            "description": "The system SHALL trigger actions from certification outcomes",
            "order": 3
          },
          {
            "id": "US-5.5",
            "title": "The system SHALL set certification cadence by risk tier",
            "description": "The system SHALL set certification cadence by risk tier",
            "order": 3
          }
        ]
      },
      {
        "id": "EPIC-6",
        "title": "Audit Evidence & Reporting",
        "description": "Build comprehensive audit reporting with who-has-access visibility",
        "order": 6,
        "steps": [
          {
            "id": "US-6.1",
            "title": "Govern the full access lifecycle, including request, approval, activation, review, revocation, and exception handling, in a repeatable and auditable manner",
            "description": "Govern the full access lifecycle, including request, approval, activation, review, revocation, and exception handling, in a repeatable and auditable manner",
            "order": 3
          },
          {
            "id": "US-6.2",
            "title": "Produce complete, attributable, and auditable evidence of access decisions sufficient to support SOX and other regulatory audits without manual reconstruction",
            "description": "Produce complete, attributable, and auditable evidence of access decisions sufficient to support SOX and other regulatory audits without manual reconstruction",
            "order": 3
          },
          {
            "id": "US-6.3",
            "title": "The system SHALL retain discovery artifacts as audit evidence",
            "description": "The system SHALL retain discovery artifacts as audit evidence",
            "order": 3
          },
          {
            "id": "US-6.4",
            "title": "The system SHALL record JIT events as audit evidence",
            "description": "The system SHALL record JIT events as audit evidence",
            "order": 3
          },
          {
            "id": "US-6.5",
            "title": "The system SHALL support on-demand audit evidence",
            "description": "The system SHALL support on-demand audit evidence",
            "order": 3
          }
        ]
      },
      {
        "id": "EPIC-7",
        "title": "IGA Platform Integration",
        "description": "Integrate with IGA platform for provisioning, certifications, and audit evidence",
        "order": 7,
        "steps": [
          {
            "id": "US-7.1",
            "title": "Define access intent, policy, and governance while delegating execution, automation, and enforcement to an enterprise IGA platform",
            "description": "Define access intent, policy, and governance while delegating execution, automation, and enforcement to an enterprise IGA platform",
            "order": 3
          },
          {
            "id": "US-7.2",
            "title": "RBAC depends on IGA for execution",
            "description": "RBAC depends on IGA for execution",
            "order": 3
          },
          {
            "id": "US-7.3",
            "title": "IGA executes provisioning, certification, JIT",
            "description": "IGA executes provisioning, certification, JIT",
            "order": 3
          },
          {
            "id": "US-7.4",
            "title": "IGA retains audit evidence for all access events",
            "description": "IGA retains audit evidence for all access events",
            "order": 3
          },
          {
            "id": "US-7.5",
            "title": "The system SHALL support hybrid identity environments spanning on-premises and SaaS",
            "description": "The system SHALL support hybrid identity environments spanning on-premises and SaaS",
            "order": 3
          },
          {
            "id": "US-7.6",
            "title": "The system SHALL support coexistence of on-premises and SaaS components with equivalent capability",
            "description": "The system SHALL support coexistence of on-premises and SaaS components with equivalent capability",
            "order": 3
          },
          {
            "id": "US-7.7",
            "title": "The system SHALL support phased migration and parallel operation with legacy IAM systems",
            "description": "The system SHALL support phased migration and parallel operation with legacy IAM systems",
            "order": 3
          },
          {
            "id": "US-7.8",
            "title": "The system SHALL support governance of connected and non-connected applications",
            "description": "The system SHALL support governance of connected and non-connected applications",
            "order": 3
          },
          {
            "id": "US-7.9",
            "title": "The system SHALL include non-connected applications in access reviews and certifications",
            "description": "The system SHALL include non-connected applications in access reviews and certifications",
            "order": 3
          },
          {
            "id": "US-7.10",
            "title": "The system SHALL support standard enterprise integration patterns (APIs, directories, DBs, files, SCIM)",
            "description": "The system SHALL support standard enterprise integration patterns (APIs, directories, DBs, files, SCIM)",
            "order": 3
          },
          {
            "id": "US-7.11",
            "title": "The system SHALL provide prebuilt connectors for common enterprise and SaaS systems",
            "description": "The system SHALL provide prebuilt connectors for common enterprise and SaaS systems",
            "order": 3
          },
          {
            "id": "US-7.12",
            "title": "The system SHALL provide extensibility mechanisms where direct connectors do not exist",
            "description": "The system SHALL provide extensibility mechanisms where direct connectors do not exist",
            "order": 3
          },
          {
            "id": "US-7.13",
            "title": "The system SHALL provide comprehensive audit logging for identity, access, and governance actions",
            "description": "The system SHALL provide comprehensive audit logging for identity, access, and governance actions",
            "order": 3
          },
          {
            "id": "US-7.14",
            "title": "The system SHALL capture approver identity, timestamps, and before/after access state",
            "description": "The system SHALL capture approver identity, timestamps, and before/after access state",
            "order": 3
          },
          {
            "id": "US-7.15",
            "title": "The system SHALL support configurable audit log retention policies",
            "description": "The system SHALL support configurable audit log retention policies",
            "order": 3
          },
          {
            "id": "US-7.16",
            "title": "The system SHALL detect access granted outside IGA-governed workflows",
            "description": "The system SHALL detect access granted outside IGA-governed workflows",
            "order": 3
          },
          {
            "id": "US-7.17",
            "title": "The system SHALL retain reconciliation actions and outcomes as audit evidence",
            "description": "The system SHALL retain reconciliation actions and outcomes as audit evidence",
            "order": 3
          },
          {
            "id": "US-7.18",
            "title": "The system SHALL support periodic access certifications by role and/or entitlement",
            "description": "The system SHALL support periodic access certifications by role and/or entitlement",
            "order": 3
          },
          {
            "id": "US-7.19",
            "title": "The system SHALL retain certification decisions with reviewer, outcome, and timestamp",
            "description": "The system SHALL retain certification decisions with reviewer, outcome, and timestamp",
            "order": 3
          },
          {
            "id": "US-7.20",
            "title": "The system SHALL support role-level certifications",
            "description": "The system SHALL support role-level certifications",
            "order": 3
          },
          {
            "id": "US-7.21",
            "title": "Automatically revoke access when removal is approved during certification",
            "description": "Automatically revoke access when removal is approved during certification",
            "order": 3
          },
          {
            "id": "US-7.22",
            "title": "The system SHALL support certification delegation, escalation, and overdue tracking",
            "description": "The system SHALL support certification delegation, escalation, and overdue tracking",
            "order": 3
          },
          {
            "id": "US-7.23",
            "title": "The system SHALL support hybrid identity environments spanning on-prem and SaaS",
            "description": "The system SHALL support hybrid identity environments spanning on-prem and SaaS",
            "order": 3
          },
          {
            "id": "US-7.24",
            "title": "The system SHALL support coexistence of on-prem and SaaS components",
            "description": "The system SHALL support coexistence of on-prem and SaaS components",
            "order": 3
          },
          {
            "id": "US-7.25",
            "title": "The system SHALL support phased migration with legacy IAM",
            "description": "The system SHALL support phased migration with legacy IAM",
            "order": 3
          },
          {
            "id": "US-7.26",
            "title": "The system SHALL ingest access from connected and non-connected apps",
            "description": "The system SHALL ingest access from connected and non-connected apps",
            "order": 3
          },
          {
            "id": "US-7.27",
            "title": "The system SHALL flag privileged access during ingestion",
            "description": "The system SHALL flag privileged access during ingestion",
            "order": 3
          },
          {
            "id": "US-7.28",
            "title": "The system SHALL support ABAC eligibility enforcement",
            "description": "The system SHALL support ABAC eligibility enforcement",
            "order": 3
          },
          {
            "id": "US-7.29",
            "title": "Auto-revoke access on attribute change",
            "description": "Auto-revoke access on attribute change",
            "order": 3
          },
          {
            "id": "US-7.30",
            "title": "The system SHALL prevent direct entitlement bypass",
            "description": "The system SHALL prevent direct entitlement bypass",
            "order": 3
          },
          {
            "id": "US-7.31",
            "title": "The system SHALL execute provisioning independent of intake UI",
            "description": "The system SHALL execute provisioning independent of intake UI",
            "order": 3
          },
          {
            "id": "US-7.32",
            "title": "The system SHALL support cross-system orchestration",
            "description": "The system SHALL support cross-system orchestration",
            "order": 3
          },
          {
            "id": "US-7.33",
            "title": "Auto-revoke access from certifications",
            "description": "Auto-revoke access from certifications",
            "order": 3
          },
          {
            "id": "US-7.34",
            "title": "The system SHALL support just-in-time privileged access",
            "description": "The system SHALL support just-in-time privileged access",
            "order": 3
          },
          {
            "id": "US-7.35",
            "title": "Automatically expire JIT access",
            "description": "Automatically expire JIT access",
            "order": 3
          },
          {
            "id": "US-7.36",
            "title": "The system SHALL retain JIT approval and expiration evidence",
            "description": "The system SHALL retain JIT approval and expiration evidence",
            "order": 3
          },
          {
            "id": "US-7.37",
            "title": "The system SHALL support role and entitlement certifications",
            "description": "The system SHALL support role and entitlement certifications",
            "order": 3
          },
          {
            "id": "US-7.38",
            "title": "The system SHALL support role-level certifications",
            "description": "The system SHALL support role-level certifications",
            "order": 3
          },
          {
            "id": "US-7.39",
            "title": "The system SHALL support escalation and overdue tracking",
            "description": "The system SHALL support escalation and overdue tracking",
            "order": 3
          },
          {
            "id": "US-7.40",
            "title": "The system SHALL capture attributable audit logs",
            "description": "The system SHALL capture attributable audit logs",
            "order": 3
          },
          {
            "id": "US-7.41",
            "title": "The system SHALL detect out-of-band access",
            "description": "The system SHALL detect out-of-band access",
            "order": 3
          },
          {
            "id": "US-7.42",
            "title": "The system SHALL retain reconciliation history",
            "description": "The system SHALL retain reconciliation history",
            "order": 3
          },
          {
            "id": "US-7.43",
            "title": "The system SHALL retain audit evidence of Workday attribute changes affecting access",
            "description": "The system SHALL retain audit evidence of Workday attribute changes affecting access",
            "order": 3
          },
          {
            "id": "US-7.44",
            "title": "The system SHALL receive access request intake from ServiceNow ITSM",
            "description": "The system SHALL receive access request intake from ServiceNow ITSM",
            "order": 3
          },
          {
            "id": "US-7.45",
            "title": "The system SHALL execute fulfillment for ServiceNow-approved access requests",
            "description": "The system SHALL execute fulfillment for ServiceNow-approved access requests",
            "order": 3
          },
          {
            "id": "US-7.46",
            "title": "The system SHALL block fulfillment of ServiceNow requests until approval is recorded",
            "description": "The system SHALL block fulfillment of ServiceNow requests until approval is recorded",
            "order": 3
          },
          {
            "id": "US-7.47",
            "title": "The system SHALL provide standard connectors",
            "description": "The system SHALL provide standard connectors",
            "order": 3
          },
          {
            "id": "US-7.48",
            "title": "The system SHALL support extensibility where connectors unavailable",
            "description": "The system SHALL support extensibility where connectors unavailable",
            "order": 3
          },
          {
            "id": "US-7.49",
            "title": "Provision via API/JDBC/REST",
            "description": "Provision via API/JDBC/REST",
            "order": 3
          },
          {
            "id": "US-7.50",
            "title": "The system SHALL support governed scripting",
            "description": "The system SHALL support governed scripting",
            "order": 3
          },
          {
            "id": "US-7.51",
            "title": "Script execution is auditable",
            "description": "Script execution is auditable",
            "order": 3
          },
          {
            "id": "US-7.52",
            "title": "The system SHALL provide 24x7 support for critical failures",
            "description": "The system SHALL provide 24x7 support for critical failures",
            "order": 3
          },
          {
            "id": "US-7.53",
            "title": "Define SLA response times for failures",
            "description": "Define SLA response times for failures",
            "order": 3
          },
          {
            "id": "US-7.54",
            "title": "Prioritize incidents impacting audit evidence",
            "description": "Prioritize incidents impacting audit evidence",
            "order": 3
          },
          {
            "id": "US-7.55",
            "title": "Scale ingestion to enterprise volumes",
            "description": "Scale ingestion to enterprise volumes",
            "order": 3
          },
          {
            "id": "US-7.56",
            "title": "The system SHALL support peak provisioning loads",
            "description": "The system SHALL support peak provisioning loads",
            "order": 3
          },
          {
            "id": "US-7.57",
            "title": "The system SHALL support large certification campaigns",
            "description": "The system SHALL support large certification campaigns",
            "order": 3
          },
          {
            "id": "US-7.58",
            "title": "The system SHALL prevent unauthorized provisioning",
            "description": "The system SHALL prevent unauthorized provisioning",
            "order": 3
          },
          {
            "id": "US-7.59",
            "title": "Protect audit logs from tampering",
            "description": "Protect audit logs from tampering",
            "order": 3
          },
          {
            "id": "US-7.60",
            "title": "Govern IGA admin access",
            "description": "Govern IGA admin access",
            "order": 3
          },
          {
            "id": "US-7.61",
            "title": "Publish release cadence",
            "description": "Publish release cadence",
            "order": 3
          },
          {
            "id": "US-7.62",
            "title": "The system SHALL support phased rollouts",
            "description": "The system SHALL support phased rollouts",
            "order": 3
          },
          {
            "id": "US-7.63",
            "title": "Preserve audit evidence across upgrades",
            "description": "Preserve audit evidence across upgrades",
            "order": 3
          }
        ]
      },
      {
        "id": "EPIC-8",
        "title": "Directory Services Integration",
        "description": "Integrate with Active Directory and Entra ID for provisioning and drift detection",
        "order": 8,
        "steps": [
          {
            "id": "US-8.1",
            "title": "The system SHALL detect and report governed directory and group membership changes",
            "description": "The system SHALL detect and report governed directory and group membership changes",
            "order": 3
          },
          {
            "id": "US-8.2",
            "title": "The system SHALL support API, directory, JDBC, file ingestion",
            "description": "The system SHALL support API, directory, JDBC, file ingestion",
            "order": 3
          },
          {
            "id": "US-8.3",
            "title": "The system SHALL ingest directory accounts and groups",
            "description": "The system SHALL ingest directory accounts and groups",
            "order": 3
          },
          {
            "id": "US-8.4",
            "title": "The system SHALL flag privileged directory groups",
            "description": "The system SHALL flag privileged directory groups",
            "order": 3
          },
          {
            "id": "US-8.5",
            "title": "Provision directory memberships",
            "description": "Provision directory memberships",
            "order": 3
          },
          {
            "id": "US-8.6",
            "title": "The system SHALL detect out-of-band directory changes",
            "description": "The system SHALL detect out-of-band directory changes",
            "order": 3
          },
          {
            "id": "US-8.7",
            "title": "The system SHALL retain directory reconciliation evidence",
            "description": "The system SHALL retain directory reconciliation evidence",
            "order": 3
          }
        ]
      },
      {
        "id": "EPIC-9",
        "title": "Workday HR Integration",
        "description": "Establish Workday as authoritative source and ingest employee attributes",
        "order": 9,
        "steps": [
          {
            "id": "US-9.1",
            "title": "The system SHALL consume joiner/mover/leaver lifecycle events from Workday HR",
            "description": "The system SHALL consume joiner/mover/leaver lifecycle events from Workday HR",
            "order": 3
          },
          {
            "id": "US-9.2",
            "title": "The system SHALL refresh Workday attributes to support timely access changes",
            "description": "The system SHALL refresh Workday attributes to support timely access changes",
            "order": 3
          }
        ]
      },
      {
        "id": "EPIC-10",
        "title": "Optional AI-powered discovery tool for role analysis and recommendations",
        "description": "Optional AI-powered discovery tool for role analysis and recommendations",
        "order": 10,
        "steps": [
          {
            "id": "US-10.1",
            "title": "The system SHALL support scalable onboarding of applications, identities, and roles without bespoke redesign or manual controls",
            "description": "The system SHALL support scalable onboarding of applications, identities, and roles without bespoke redesign or manual controls",
            "order": 3
          }
        ]
      }
    ],
    "order": 1
  }
];
